openapi: 3.0.2
info:
  title: game-chat REST API
  version: '1.1.1'
  description: |
    REST API Documentation for ft_transcendence.
    Under heavy development. Expect breaking changes.

servers:
  - url: https://localhost
  - url: https://playpong.duckdns.org

tags:
  - name: Status
  - name: User

paths:
  /game/status:
    get:
      tags:
        - Status
      summary: Check Heartbeat Status
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Service is up and running
        '401':
          description: Unauthorized
        '503':
          description: Service is down or unhealthy
  /game/user:
    post:
      tags:
        - User
      summary: add new User
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUserRequest'
      responses:
        '200':
          description: OK
        '400':
          description: Bad request (for example user already exists, input validation error)
          content:
            text/plain:
              schema:
                type: string
                example: "input validation error"
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /game/user/avatar:
    put:
      tags:
        - User
      summary: Update Avatar
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: "https://localhost/static/avatar/abcdef1234567890.png"
      responses:
        '200':
          description: OK
        '400':
          description: User not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /game/user/alias:
    put:
      tags:
        - User
      summary: Update Alias
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: "moon-dog.jpg"
      responses:
        '200':
          description: OK
        '400':
          description: Alias already taken
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    NewUserRequest:
      type: object
      required:
        - username
        - avatar
      properties:
        username:
          type: string
          example: "username"
        avatar:
          type: string
          example: "https://localhost/static/avatar/abcdef1234567890.png"
