openapi: 3.0.2
info:
  title: game-chat REST API
  version: '1.0.13'
  description: |
    REST API Documentation for ft_transcendence.
    Under heavy development. Expect breaking changes.

servers:
  - url: https://localhost/game
  - url: https://playpong.duckdns.org/game

paths:
  /test:
    get:
      tags:
        - Test
      responses:
        '200':
          description: OK