openapi: 3.0.2
info:
  title: static REST API
  version: '1.0.0'

  description: |
    REST API Documentation for ft_transcendence.
    Under heavy development - expect breaking changes.

servers:
  - url: https://localhost
  - url: https://playpong.duckdns.org

tags:
  - name: Status
  - name: Avatar

paths:
  /static/avatar:
    get:
      tags:
        - Avatar
      summary: Get avatar
      description: Get avatar by user id
      parameters:
        - name: id
          in: query
          description: User id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  avatar:
                    type: string
                    format: binary
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error