openapi: 3.0.2
info:
  title: vault REST API
  version: '1.0.13'
  description: |
    REST API Documentation for ft_transcendence.
    Under heavy development. Expect breaking changes.

servers:
  - url: https://localhost
    description: Localhost server
  - url: https://playpong.duckdns.org
    description: Production server (main branch)

paths:
  /vault/test:
    get:
      tags:
        - Test
      responses:
        '200':
          description: OK