version: "3"

services:

# PROXY SERVER
  nginx:
    env_file: .env
    container_name: nginx
    build:
      context: nginx
      args:
        CURRENT_HOST: ${CURRENT_HOST}
    volumes:
      - ./nginx/root:/usr/share/nginx/html
      - ./nginx/nginx.conf.template:/nginx.conf.template
      - ./.cert/:/etc/nginx/ssl/
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - network
    depends_on:
      - auth_backend
      - auth_db
      - game_chat_frontend
      - game_chat_backend
      - game_chat_db


# SERVICE AUTH
  auth_backend:
    env_file: .env
    container_name: auth_backend
    build: 
      context: auth
    volumes:
      - ./auth:/code
    networks:
      - network
    restart: always
    depends_on:
      auth_db:
        condition: service_healthy
    expose:
      - 8000
  auth_db:
    container_name: auth_db
    build:
      context: postgres
    user: postgres
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - network
    volumes:
      - auth_db:/var/lib/postgresql/data/
    expose:
      - 5432


# SERVICE GAME_CHAT
  game_chat_frontend:
    env_file: .env
    container_name: game_chat_frontend
    build:
      context: game_chat/frontend
    # user: 1000:1000
    volumes:
      - ./game_chat/frontend/src:/usr/share/nginx/html
      - ./game_chat/frontend/nginx.conf.template:/nginx.conf.template
    restart: always
    networks:
      - network
    depends_on:
      - game_chat_backend
    expose:
      - 4242
  game_chat_backend:
    env_file: .env
    container_name: game_chat_backend
    # user: 1000:1000
    build: 
      context: game_chat/backend
    volumes:
      - ./game_chat/backend:/code
    networks:
      - network
    restart: always
    depends_on:
      game_chat_db:
        condition: service_healthy
    expose:
      - 6969
  game_chat_db:
    container_name: game_chat_db
    build:
      context: postgres
    user: postgres
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - network
    volumes:
      - game_chat_db:/var/lib/postgresql/data/
    expose:
      - 5432


volumes:
  game_chat_db:
  auth_db:

networks:
  network:
    driver: bridge
