openapi: '3.1.0'
info:
  title: auth ms API
  version: '1.0'
description: openAPI specs for ft_transcendence auth microservice
servers:
  - url: https://localhost/api/v1
paths:
  /login:
    post:
      operationId: login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'