openapi: '3.0.2'
info:
  title: ft_transcendence
  version: '1.0'
servers:
  - url: https://playpong.duckdns.org/api/v1/

components:
  schemas:
    name:
      type: object
      properties:
        property:
          type: integerpaths: {}
