name: ms-auth2html

on:
  push:
    branches:
      - dev
    paths:
      - 'docs/openapi/ms-auth.yaml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate HTML Documentation and Commit Changes
      run: |
        npm i api2html -g
        api2html -o ./docs/openapi/ms-auth.html -c ./ms_frontend/root/public/images/moon-dog.jpg -l javascript,python ./docs/openapi/ms-auth.yaml

        # Create the index.html file
        cat > ./docs/openapi/index.html <<EOL
        <!DOCTYPE html>
        <html>
        <head>
          <title>OpenAPI Documentation</title>
          <style>
            body {
              margin: 0;
              font-family: Arial, sans-serif;
            }
        
            .wrapper {
              display: flex;
              flex-direction: column;
              min-height: 100vh;
            }
        
            .top-frame {
              background-color: #333;
              color: #fff;
              padding: 10px;
              display: flex;
              justify-content: center;
              position: sticky;
              top: 0;
              z-index: 999;
            }
        
            .top-frame a {
              color: #fff;
              text-decoration: none;
              margin: 0 10px;
              padding: 5px 10px;
              border-radius: 5px;
              transition: background-color 0.3s;
              font-size: 18px;
              font-weight: bold;
              background-color: #555; /* default background color */
            }
        
            .top-frame a:hover {
              background-color: #777; /* lighter background on hover */
            }
        
            .top-frame a:not(:last-child) {
              <!-- border-right: 2px solid #0e0e0e; /* visually dividing links */ -->
            }
        
            .content {
              flex-grow: 1;
              padding: 20px;
              font-size: 16px; /* default font size for content */
            }
        
            h1, h2, h3, h4, h5, h6 {
              font-weight: bold;
            }
          </style>
        </head>
        <body>
          <div class="wrapper">
            <div class="top-frame">
              <a href="#" onclick="loadContent('ms-auth')">ms-auth</a>
              <a href="#" onclick="loadContent('game-chat')">game-chat</a>
              <a href="#" onclick="loadContent('vault')">vault</a>
              <a href="#" onclick="loadContent('api-gateway')">api-gateway</a>
            </div>
        
            <div class="content" id="content">
              <!-- Content will be loaded dynamically here -->
            </div>
          </div>
        
          <script>
            document.addEventListener('DOMContentLoaded', function () {
              loadContent('ms-auth');
            });
        
            function loadContent(moduleName) {
              var url = moduleName + '.html';
              fetch(url)
                .then(response => response.text())
                .then(data => {
                  document.getElementById('content').innerHTML = data;
                })
                .catch(error => console.error('Error:', error));
            }
          </script>
        </body>
        </html>
        EOL

        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git add ./docs/openapi/ms-auth.html
        git add ./docs/openapi/index.html
        git commit -m 'Update OpenAPI documentation for ms-auth'
        git push

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/openapi/
