name: ft_jwt publish to PyPI

on:
  push:
    branches:
      - jwt
    paths:
      - 'auth/ft_jwt/ft_jwt/ft_jwt.py'

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install build twine
    - name: Increment version
      run: |
        import re
        with open('setup.py', 'r') as f:
            content = f.read()
        match = re.search(r"version='(\d+\.\d+\.\d+)'", content)
        if match:
            old_version = match.group(1)
            major, minor, patch = map(int, old_version.split('.'))
            patch += 1
            new_version = f"{major}.{minor}.{patch}"
            content = re.sub(r"version='(\d+\.\d+\.\d+)'", f"version='{new_version}'", content)
        with open('setup.py', 'w') as f:
            f.write(content)
        print(f"New version: {new_version}")
    - name: Build package
      run: python -m build
    - name: ft_jwt publish to PyPI
      env:
        PYPI_USERNAME: __token__
        PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*